<?php

namespace ContainerBxwxNLi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ts1FrJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ts1Fr_J' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ts1Fr_J'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'refServ' => ['privates', 'App\\Repository\\RipsTablaReferenciaServicioRepository', 'getRipsTablaReferenciaServicioRepositoryService', true],
        ], [
            'refServ' => 'App\\Repository\\RipsTablaReferenciaServicioRepository',
        ]);
    }
}
