<?php

namespace ContainerBxwxNLi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_U3GyUS7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.u3GyUS7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.u3GyUS7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'procedimientos' => ['privates', 'App\\Repository\\AsConsultasProcedimientosRepository', 'getAsConsultasProcedimientosRepositoryService', true],
        ], [
            'procedimientos' => 'App\\Repository\\AsConsultasProcedimientosRepository',
        ]);
    }
}
