<?php

namespace ContainerBxwxNLi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QjbHuocService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QjbHuoc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QjbHuoc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'consult' => ['privates', 'App\\Repository\\AsConsultasProcedimientosRepository', 'getAsConsultasProcedimientosRepositoryService', true],
        ], [
            'consult' => 'App\\Repository\\AsConsultasProcedimientosRepository',
        ]);
    }
}
