<?php

namespace ContainerBxwxNLi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getValidationServicesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\ValidationServices' shared autowired service.
     *
     * @return \App\Service\ValidationServices
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ValidationServices.php';

        return $container->privates['App\\Service\\ValidationServices'] = new \App\Service\ValidationServices(($container->services['.container.private.validator'] ?? $container->get_Container_Private_ValidatorService()));
    }
}
