<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'App__Entity__AsCie10__CLASSMETADATA__' => 0,
'App__Entity__AsConsultasProcedimientos__CLASSMETADATA__' => 1,
'App__Entity__AsCups__CLASSMETADATA__' => 2,
'App__Entity__RipsTablaReferenciaCausaExternaV2__CLASSMETADATA__' => 3,
'App__Entity__RipsTablaReferenciaFinalidadConsultaV2__CLASSMETADATA__' => 4,
'App__Entity__RipsTablaReferenciaServicio__CLASSMETADATA__' => 5,

], [

0 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Id\\SequenceGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\SequenceGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\AsCie10',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\AsCie10Repository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    2,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'cie_10' => $o[2],
                        'nombre' => $o[3],
                        'created_at' => $o[4],
                        'updated_at' => $o[5],
                        'nombre_ingles' => $o[6],
                        'sistema' => $o[7],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'cie_10' => 'cie_10',
                        'nombre' => 'nombre',
                        'created_at' => 'created_at',
                        'updated_at' => 'updated_at',
                        'nombre_ingles' => 'nombre_ingles',
                        'sistema' => 'sistema',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'cie_10' => 'cie_10',
                        'nombre' => 'nombre',
                        'created_at' => 'created_at',
                        'updated_at' => 'updated_at',
                        'nombre_ingles' => 'nombre_ingles',
                        'sistema' => 'sistema',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'as_cie10',
                    ],
                ],
                'associationMappings' => [
                    [
                        'consultasProcedimientos' => $o[8],
                    ],
                ],
                'idGenerator' => [
                    $o[9],
                ],
                'sequenceGeneratorDefinition' => [
                    [
                        'sequenceName' => 'as_cie10_id_seq',
                        'allocationSize' => '1',
                        'initialValue' => '1',
                    ],
                ],
                'name' => [
                    'App\\Entity\\AsCie10',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'bigint',
                    'string',
                    'string',
                    'datetime_immutable',
                    'datetime_immutable',
                    'string',
                    'string',
                ],
                'fieldName' => [
                    1 => 'id',
                    'cie_10',
                    'nombre',
                    'created_at',
                    'updated_at',
                    'nombre_ingles',
                    'sistema',
                ],
                'columnName' => [
                    1 => 'id',
                    'cie_10',
                    'nombre',
                    'created_at',
                    'updated_at',
                    'nombre_ingles',
                    'sistema',
                ],
                'length' => [
                    2 => 20,
                    255,
                    6 => 255,
                    255,
                ],
                'nullable' => [
                    2 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                'fetch' => [
                    8 => 2,
                ],
                'sourceEntity' => [
                    8 => 'App\\Entity\\AsCie10',
                ],
                'mappedBy' => [
                    8 => 'diagnostico_defaults',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    8 => 'consultasProcedimientos',
                ],
                'targetEntity' => [
                    8 => 'App\\Entity\\AsConsultasProcedimientos',
                ],
            ],
        ],
        $o[0],
        [
            -9 => [
                'allocationSize' => 1,
                'sequenceName' => 'as_cie10_id_seq',
            ],
        ]
    );
},
1 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone ($p['Doctrine\\ORM\\Id\\SequenceGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\SequenceGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\AsConsultasProcedimientos',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\AsConsultasProcedimientosRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    2,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'tipo_servicio' => $o[2],
                        'informe_oportunidad' => $o[3],
                        'tipo_cita' => $o[4],
                        'created_by' => $o[5],
                        'created_at' => $o[6],
                        'tipo_diagnostico' => $o[7],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'tipo_servicio' => 'tipo_servicio',
                        'informe_oportunidad' => 'informe_oportunidad',
                        'tipo_cita' => 'tipo_cita',
                        'created_by' => 'created_by',
                        'created_at' => 'created_at',
                        'tipo_diagnostico' => 'tipo_diagnostico',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'tipo_servicio' => 'tipo_servicio',
                        'informe_oportunidad' => 'informe_oportunidad',
                        'tipo_cita' => 'tipo_cita',
                        'created_by' => 'created_by',
                        'created_at' => 'created_at',
                        'tipo_diagnostico' => 'tipo_diagnostico',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'as_consultas_procedimientos',
                    ],
                ],
                'lifecycleCallbacks' => [
                    [
                        'prePersist' => [
                            'setCreatedAt',
                        ],
                    ],
                ],
                'associationMappings' => [
                    [
                        'cups' => $o[8],
                        'diagnostico_defaults' => $o[10],
                        'finalidad' => $o[12],
                        'causa_externa' => $o[14],
                        'servicio_rips_code' => $o[16],
                    ],
                ],
                'idGenerator' => [
                    $o[18],
                ],
                'sequenceGeneratorDefinition' => [
                    [
                        'sequenceName' => 'as_consultas_procedimientos_id_seq',
                        'allocationSize' => '1',
                        'initialValue' => '1',
                    ],
                ],
                'name' => [
                    'App\\Entity\\AsConsultasProcedimientos',
                    9 => 'cups',
                    11 => 'diagnostico_defaults',
                    13 => 'finalidad',
                    15 => 'causa_externa',
                    17 => 'servicio_rips_code',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'boolean',
                    'integer',
                    'string',
                    'datetime_immutable',
                    'string',
                ],
                'fieldName' => [
                    1 => 'id',
                    'tipo_servicio',
                    'informe_oportunidad',
                    'tipo_cita',
                    'created_by',
                    'created_at',
                    'tipo_diagnostico',
                ],
                'columnName' => [
                    1 => 'id',
                    'tipo_servicio',
                    'informe_oportunidad',
                    'tipo_cita',
                    'created_by',
                    'created_at',
                    'tipo_diagnostico',
                ],
                'length' => [
                    2 => 250,
                    5 => 255,
                    7 => 255,
                ],
                'nullable' => [
                    2 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    9 => false,
                    11 => false,
                    13 => true,
                    15 => true,
                    17 => false,
                ],
                'fetch' => [
                    8 => 3,
                    10 => 3,
                    12 => 3,
                    14 => 3,
                    16 => 3,
                ],
                'sourceEntity' => [
                    8 => 'App\\Entity\\AsConsultasProcedimientos',
                    10 => 'App\\Entity\\AsConsultasProcedimientos',
                    12 => 'App\\Entity\\AsConsultasProcedimientos',
                    14 => 'App\\Entity\\AsConsultasProcedimientos',
                    16 => 'App\\Entity\\AsConsultasProcedimientos',
                ],
                'inversedBy' => [
                    8 => 'consultasProcedimientos',
                    10 => 'consultasProcedimientos',
                    12 => 'consultasProcedimientos',
                    14 => 'consultasProcedimientos',
                    16 => 'consultasProcedimientos',
                ],
                'sourceToTargetKeyColumns' => [
                    8 => [
                        'cups' => 'id',
                    ],
                    10 => [
                        'diagnostico_defaults' => 'id',
                    ],
                    12 => [
                        'finalidad' => 'codigo',
                    ],
                    14 => [
                        'causa_externa' => 'codigo',
                    ],
                    16 => [
                        'servicio_rips_code' => 'codigo',
                    ],
                ],
                'targetToSourceKeyColumns' => [
                    8 => [
                        'id' => 'cups',
                    ],
                    10 => [
                        'id' => 'diagnostico_defaults',
                    ],
                    12 => [
                        'codigo' => 'finalidad',
                    ],
                    14 => [
                        'codigo' => 'causa_externa',
                    ],
                    16 => [
                        'codigo' => 'servicio_rips_code',
                    ],
                ],
                'joinColumns' => [
                    8 => [
                        $o[9],
                    ],
                    10 => [
                        $o[11],
                    ],
                    12 => [
                        $o[13],
                    ],
                    14 => [
                        $o[15],
                    ],
                    16 => [
                        $o[17],
                    ],
                ],
                'joinColumnFieldNames' => [
                    8 => [
                        'cups' => 'cups',
                    ],
                    10 => [
                        'diagnostico_defaults' => 'diagnostico_defaults',
                    ],
                    12 => [
                        'finalidad' => 'finalidad',
                    ],
                    14 => [
                        'causa_externa' => 'causa_externa',
                    ],
                    16 => [
                        'servicio_rips_code' => 'servicio_rips_code',
                    ],
                ],
                'unique' => [
                    9 => false,
                    11 => false,
                    13 => false,
                    15 => false,
                    17 => false,
                ],
                'onDelete' => [
                    9 => 'CASCADE',
                    11 => 'CASCADE',
                    17 => 'CASCADE',
                ],
                'referencedColumnName' => [
                    9 => 'id',
                    11 => 'id',
                    13 => 'codigo',
                    15 => 'codigo',
                    17 => 'codigo',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    8 => 'cups',
                    10 => 'diagnostico_defaults',
                    12 => 'finalidad',
                    14 => 'causa_externa',
                    16 => 'servicio_rips_code',
                ],
                'targetEntity' => [
                    8 => 'App\\Entity\\AsCups',
                    10 => 'App\\Entity\\AsCie10',
                    12 => 'App\\Entity\\RipsTablaReferenciaFinalidadConsultaV2',
                    14 => 'App\\Entity\\RipsTablaReferenciaCausaExternaV2',
                    16 => 'App\\Entity\\RipsTablaReferenciaServicio',
                ],
            ],
        ],
        $o[0],
        [
            -18 => [
                'allocationSize' => 1,
                'sequenceName' => 'as_consultas_procedimientos_id_seq',
            ],
        ]
    );
},
2 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Id\\SequenceGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\SequenceGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\AsCups',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\AsCupsRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    2,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'seccion' => $o[2],
                        'capitulo' => $o[3],
                        'codigo_cups' => $o[4],
                        'descripcion_cups' => $o[5],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'seccion' => 'seccion',
                        'capitulo' => 'capitulo',
                        'codigo_cups' => 'codigo_cups',
                        'descripcion_cups' => 'descripcion_cups',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'seccion' => 'seccion',
                        'capitulo' => 'capitulo',
                        'codigo_cups' => 'codigo_cups',
                        'descripcion_cups' => 'descripcion_cups',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'as_cups',
                    ],
                ],
                'associationMappings' => [
                    [
                        'consultasProcedimientos' => $o[6],
                    ],
                ],
                'idGenerator' => [
                    $o[7],
                ],
                'sequenceGeneratorDefinition' => [
                    [
                        'sequenceName' => 'as_cups_id_seq',
                        'allocationSize' => '1',
                        'initialValue' => '1',
                    ],
                ],
                'name' => [
                    'App\\Entity\\AsCups',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'string',
                    'string',
                    'string',
                ],
                'fieldName' => [
                    1 => 'id',
                    'seccion',
                    'capitulo',
                    'codigo_cups',
                    'descripcion_cups',
                ],
                'columnName' => [
                    1 => 'id',
                    'seccion',
                    'capitulo',
                    'codigo_cups',
                    'descripcion_cups',
                ],
                'length' => [
                    2 => 255,
                    255,
                    6,
                    255,
                ],
                'nullable' => [
                    2 => true,
                    true,
                    true,
                    true,
                ],
                'fetch' => [
                    6 => 2,
                ],
                'sourceEntity' => [
                    6 => 'App\\Entity\\AsCups',
                ],
                'mappedBy' => [
                    6 => 'cups',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    6 => 'consultasProcedimientos',
                ],
                'targetEntity' => [
                    6 => 'App\\Entity\\AsConsultasProcedimientos',
                ],
            ],
        ],
        $o[0],
        [
            -7 => [
                'allocationSize' => 1,
                'sequenceName' => 'as_cups_id_seq',
            ],
        ]
    );
},
3 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Id\\AssignedGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\AssignedGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\RipsTablaReferenciaCausaExternaV2',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\RipsTablaReferenciaCausaExternaV2Repository',
                ],
                'identifier' => [
                    [
                        'codigo',
                    ],
                ],
                'fieldMappings' => [
                    [
                        'codigo' => $o[1],
                        'nombre' => $o[2],
                    ],
                ],
                'fieldNames' => [
                    [
                        'codigo' => 'codigo',
                        'nombre' => 'nombre',
                    ],
                ],
                'columnNames' => [
                    [
                        'codigo' => 'codigo',
                        'nombre' => 'nombre',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'rips_tabla_referencia_causa_externa_v2',
                    ],
                ],
                'associationMappings' => [
                    [
                        'consultasProcedimientos' => $o[3],
                    ],
                ],
                'idGenerator' => [
                    $o[4],
                ],
                'name' => [
                    'App\\Entity\\RipsTablaReferenciaCausaExternaV2',
                ],
                'length' => [
                    1 => 250,
                    250,
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'string',
                    'string',
                ],
                'fieldName' => [
                    1 => 'codigo',
                    'nombre',
                ],
                'columnName' => [
                    1 => 'codigo',
                    'nombre',
                ],
                'nullable' => [
                    2 => true,
                ],
                'fetch' => [
                    3 => 2,
                ],
                'sourceEntity' => [
                    3 => 'App\\Entity\\RipsTablaReferenciaCausaExternaV2',
                ],
                'mappedBy' => [
                    3 => 'causa_externa',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    3 => 'consultasProcedimientos',
                ],
                'targetEntity' => [
                    3 => 'App\\Entity\\AsConsultasProcedimientos',
                ],
            ],
        ],
        $o[0],
        []
    );
},
4 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Id\\AssignedGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\AssignedGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\RipsTablaReferenciaFinalidadConsultaV2',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\RipsTablaReferenciaFinalidadConsultaV2Repository',
                ],
                'identifier' => [
                    [
                        'codigo',
                    ],
                ],
                'fieldMappings' => [
                    [
                        'codigo' => $o[1],
                        'nombre' => $o[2],
                    ],
                ],
                'fieldNames' => [
                    [
                        'codigo' => 'codigo',
                        'nombre' => 'nombre',
                    ],
                ],
                'columnNames' => [
                    [
                        'codigo' => 'codigo',
                        'nombre' => 'nombre',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'rips_tabla_referencia_finalidad_consulta_v2',
                    ],
                ],
                'associationMappings' => [
                    [
                        'consultasProcedimientos' => $o[3],
                    ],
                ],
                'idGenerator' => [
                    $o[4],
                ],
                'name' => [
                    'App\\Entity\\RipsTablaReferenciaFinalidadConsultaV2',
                ],
                'length' => [
                    1 => 250,
                    250,
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'string',
                    'string',
                ],
                'fieldName' => [
                    1 => 'codigo',
                    'nombre',
                ],
                'columnName' => [
                    1 => 'codigo',
                    'nombre',
                ],
                'nullable' => [
                    2 => true,
                ],
                'fetch' => [
                    3 => 2,
                ],
                'sourceEntity' => [
                    3 => 'App\\Entity\\RipsTablaReferenciaFinalidadConsultaV2',
                ],
                'mappedBy' => [
                    3 => 'finalidad',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    3 => 'consultasProcedimientos',
                ],
                'targetEntity' => [
                    3 => 'App\\Entity\\AsConsultasProcedimientos',
                ],
            ],
        ],
        $o[0],
        []
    );
},
5 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Id\\AssignedGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\AssignedGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\RipsTablaReferenciaServicio',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\RipsTablaReferenciaServicioRepository',
                ],
                'identifier' => [
                    [
                        'codigo',
                    ],
                ],
                'fieldMappings' => [
                    [
                        'codigo' => $o[1],
                        'nombre' => $o[2],
                        'grupo_codigo' => $o[3],
                        'grupo_nombre' => $o[4],
                    ],
                ],
                'fieldNames' => [
                    [
                        'codigo' => 'codigo',
                        'nombre' => 'nombre',
                        'grupo_codigo' => 'grupo_codigo',
                        'grupo_nombre' => 'grupo_nombre',
                    ],
                ],
                'columnNames' => [
                    [
                        'codigo' => 'codigo',
                        'nombre' => 'nombre',
                        'grupo_codigo' => 'grupo_codigo',
                        'grupo_nombre' => 'grupo_nombre',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'rips_tabla_referencia_servicio',
                    ],
                ],
                'associationMappings' => [
                    [
                        'consultasProcedimientos' => $o[5],
                    ],
                ],
                'idGenerator' => [
                    $o[6],
                ],
                'name' => [
                    'App\\Entity\\RipsTablaReferenciaServicio',
                ],
                'length' => [
                    1 => 250,
                    250,
                    250,
                    250,
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'string',
                    'string',
                    'string',
                    'string',
                ],
                'fieldName' => [
                    1 => 'codigo',
                    'nombre',
                    'grupo_codigo',
                    'grupo_nombre',
                ],
                'columnName' => [
                    1 => 'codigo',
                    'nombre',
                    'grupo_codigo',
                    'grupo_nombre',
                ],
                'fetch' => [
                    5 => 2,
                ],
                'sourceEntity' => [
                    5 => 'App\\Entity\\RipsTablaReferenciaServicio',
                ],
                'mappedBy' => [
                    5 => 'servicio_rips_code',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    5 => 'consultasProcedimientos',
                ],
                'targetEntity' => [
                    5 => 'App\\Entity\\AsConsultasProcedimientos',
                ],
            ],
        ],
        $o[0],
        []
    );
},

]];
