<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM0Kcdr9\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM0Kcdr9/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerM0Kcdr9.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerM0Kcdr9\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerM0Kcdr9\App_KernelProdContainer([
    'container.build_hash' => 'M0Kcdr9',
    'container.build_id' => '03c319da',
    'container.build_time' => 1737961657,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM0Kcdr9');
