<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'index' => [[], ['_controller' => 'App\\Controller\\ListCupsRipsController::index'], [], [['text', '/']], [], [], []],
    'get_list_diagnostic' => [[], ['_controller' => 'App\\Controller\\ListCupsRipsController::diagnosticoSuggestions'], [], [['text', '/list-diagnostic']], [], [], []],
    'get_list_external_cause' => [[], ['_controller' => 'App\\Controller\\ListCupsRipsController::causaExterna'], [], [['text', '/list-external-cause']], [], [], []],
    'get_list_finality' => [[], ['_controller' => 'App\\Controller\\ListCupsRipsController::finalidadData'], [], [['text', '/list-finality']], [], [], []],
    'get_list_as_cups' => [[], ['_controller' => 'App\\Controller\\ListCupsRipsController::cupsData'], [], [['text', '/list-cups']], [], [], []],
    'export_data' => [[], ['_controller' => 'App\\Controller\\ListCupsRipsController::exportData'], [], [['text', '/export']], [], [], []],
    'get_as_consults' => [[], ['_controller' => 'App\\Controller\\RoutesController::fetchData'], [], [['text', '/get-consults']], [], [], []],
    'get_as_consult_by_id' => [['id'], ['_controller' => 'App\\Controller\\RoutesController::edit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/get-consult']], [], [], []],
    'create_as_consult' => [[], ['_controller' => 'App\\Controller\\RoutesController::createAsConsultasProcedimientos'], [], [['text', '/create-consult']], [], [], []],
    'update_as_consult' => [['id'], ['_controller' => 'App\\Controller\\RoutesController::updateAsConsultasProcedimientos'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/update-consult']], [], [], []],
    'delete_as_consult' => [['id'], ['_controller' => 'App\\Controller\\RoutesController::deleteAsConsultasProcedimientos'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/delete-consult']], [], [], []],
];
