<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AsCie10 extends \App\Entity\AsCie10 implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'cie_10' => [parent::class, 'cie_10', null],
        "\0".parent::class."\0".'consultasProcedimientos' => [parent::class, 'consultasProcedimientos', null],
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'nombre' => [parent::class, 'nombre', null],
        "\0".parent::class."\0".'nombre_ingles' => [parent::class, 'nombre_ingles', null],
        "\0".parent::class."\0".'sistema' => [parent::class, 'sistema', null],
        "\0".parent::class."\0".'updated_at' => [parent::class, 'updated_at', null],
        'cie_10' => [parent::class, 'cie_10', null],
        'consultasProcedimientos' => [parent::class, 'consultasProcedimientos', null],
        'created_at' => [parent::class, 'created_at', null],
        'id' => [parent::class, 'id', null],
        'nombre' => [parent::class, 'nombre', null],
        'nombre_ingles' => [parent::class, 'nombre_ingles', null],
        'sistema' => [parent::class, 'sistema', null],
        'updated_at' => [parent::class, 'updated_at', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
