<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class RipsTablaReferenciaFinalidadConsultaV2 extends \App\Entity\RipsTablaReferenciaFinalidadConsultaV2 implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'codigo' => [parent::class, 'codigo', null],
        "\0".parent::class."\0".'consultasProcedimientos' => [parent::class, 'consultasProcedimientos', null],
        "\0".parent::class."\0".'nombre' => [parent::class, 'nombre', null],
        'codigo' => [parent::class, 'codigo', null],
        'consultasProcedimientos' => [parent::class, 'consultasProcedimientos', null],
        'nombre' => [parent::class, 'nombre', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
