<?php

namespace ContainerM0Kcdr9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAsConsultasProcedimientosTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\AsConsultasProcedimientosType' shared autowired service.
     *
     * @return \App\Form\AsConsultasProcedimientosType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\AsConsultasProcedimientosType'] = new \App\Form\AsConsultasProcedimientosType(($container->privates['App\\Repository\\AsCie10Repository'] ?? $container->load('getAsCie10RepositoryService')), ($container->privates['App\\Repository\\RipsTablaReferenciaCausaExternaV2Repository'] ?? $container->load('getRipsTablaReferenciaCausaExternaV2RepositoryService')), ($container->privates['App\\Repository\\RipsTablaReferenciaFinalidadConsultaV2Repository'] ?? $container->load('getRipsTablaReferenciaFinalidadConsultaV2RepositoryService')));
    }
}
