<?php

namespace ContainerM0Kcdr9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAsCupsRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\AsCupsRepository' shared autowired service.
     *
     * @return \App\Repository\AsCupsRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\AsCupsRepository'] = new \App\Repository\AsCupsRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
