<?php

namespace ContainerM0Kcdr9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getListCupsRipsControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\ListCupsRipsController' shared autowired service.
     *
     * @return \App\Controller\ListCupsRipsController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\ListCupsRipsController'] = $instance = new \App\Controller\ListCupsRipsController();

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('App\\Controller\\ListCupsRipsController', $container));

        return $instance;
    }
}
