<?php

namespace ContainerM0Kcdr9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRipsTablaReferenciaServicioRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\RipsTablaReferenciaServicioRepository' shared autowired service.
     *
     * @return \App\Repository\RipsTablaReferenciaServicioRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\RipsTablaReferenciaServicioRepository'] = new \App\Repository\RipsTablaReferenciaServicioRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
