<?php

namespace ContainerM0Kcdr9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getValidationServicesService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\ValidationServices' shared autowired service.
     *
     * @return \App\Service\ValidationServices
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\ValidationServices'] = new \App\Service\ValidationServices(($container->services['.container.private.validator'] ?? $container->load('get_Container_Private_ValidatorService')));
    }
}
