<?php

namespace ContainerIJdfZVd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4Y5PVhxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4Y5PVhx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4Y5PVhx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ExampleController::causaExterna' => ['privates', '.service_locator.B1F7hHL', 'get_ServiceLocator_B1F7hHLService', true],
            'App\\Controller\\ExampleController::cupsData' => ['privates', '.service_locator.XI8WfFs', 'get_ServiceLocator_XI8WfFsService', true],
            'App\\Controller\\ExampleController::diagnosticoSuggestions' => ['privates', '.service_locator.xaWBN7T', 'get_ServiceLocator_XaWBN7TService', true],
            'App\\Controller\\ExampleController::exportData' => ['privates', '.service_locator.u3GyUS7', 'get_ServiceLocator_U3GyUS7Service', true],
            'App\\Controller\\ExampleController::finalidadData' => ['privates', '.service_locator.zIDK9pt', 'get_ServiceLocator_ZIDK9ptService', true],
            'App\\Controller\\ExampleController::index' => ['privates', '.service_locator.Ts1Fr_J', 'get_ServiceLocator_Ts1FrJService', true],
            'App\\Controller\\RoutesController::createAsConsultasProcedimientos' => ['privates', '.service_locator.NUbdc9N', 'get_ServiceLocator_NUbdc9NService', true],
            'App\\Controller\\RoutesController::deleteAsConsultasProcedimientos' => ['privates', '.service_locator.AMtaBc3', 'get_ServiceLocator_AMtaBc3Service', true],
            'App\\Controller\\RoutesController::edit' => ['privates', '.service_locator.QjbHuoc', 'get_ServiceLocator_QjbHuocService', true],
            'App\\Controller\\RoutesController::fetchData' => ['privates', '.service_locator.u3GyUS7', 'get_ServiceLocator_U3GyUS7Service', true],
            'App\\Controller\\RoutesController::typesValidation' => ['privates', '.service_locator.zjQkmuM', 'get_ServiceLocator_ZjQkmuMService', true],
            'App\\Controller\\RoutesController::updateAsConsultasProcedimientos' => ['privates', '.service_locator.2XT1KAK', 'get_ServiceLocator_2XT1KAKService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\ExampleController:causaExterna' => ['privates', '.service_locator.B1F7hHL', 'get_ServiceLocator_B1F7hHLService', true],
            'App\\Controller\\ExampleController:cupsData' => ['privates', '.service_locator.XI8WfFs', 'get_ServiceLocator_XI8WfFsService', true],
            'App\\Controller\\ExampleController:diagnosticoSuggestions' => ['privates', '.service_locator.xaWBN7T', 'get_ServiceLocator_XaWBN7TService', true],
            'App\\Controller\\ExampleController:exportData' => ['privates', '.service_locator.u3GyUS7', 'get_ServiceLocator_U3GyUS7Service', true],
            'App\\Controller\\ExampleController:finalidadData' => ['privates', '.service_locator.zIDK9pt', 'get_ServiceLocator_ZIDK9ptService', true],
            'App\\Controller\\ExampleController:index' => ['privates', '.service_locator.Ts1Fr_J', 'get_ServiceLocator_Ts1FrJService', true],
            'App\\Controller\\RoutesController:createAsConsultasProcedimientos' => ['privates', '.service_locator.NUbdc9N', 'get_ServiceLocator_NUbdc9NService', true],
            'App\\Controller\\RoutesController:deleteAsConsultasProcedimientos' => ['privates', '.service_locator.AMtaBc3', 'get_ServiceLocator_AMtaBc3Service', true],
            'App\\Controller\\RoutesController:edit' => ['privates', '.service_locator.QjbHuoc', 'get_ServiceLocator_QjbHuocService', true],
            'App\\Controller\\RoutesController:fetchData' => ['privates', '.service_locator.u3GyUS7', 'get_ServiceLocator_U3GyUS7Service', true],
            'App\\Controller\\RoutesController:typesValidation' => ['privates', '.service_locator.zjQkmuM', 'get_ServiceLocator_ZjQkmuMService', true],
            'App\\Controller\\RoutesController:updateAsConsultasProcedimientos' => ['privates', '.service_locator.2XT1KAK', 'get_ServiceLocator_2XT1KAKService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\ExampleController::causaExterna' => '?',
            'App\\Controller\\ExampleController::cupsData' => '?',
            'App\\Controller\\ExampleController::diagnosticoSuggestions' => '?',
            'App\\Controller\\ExampleController::exportData' => '?',
            'App\\Controller\\ExampleController::finalidadData' => '?',
            'App\\Controller\\ExampleController::index' => '?',
            'App\\Controller\\RoutesController::createAsConsultasProcedimientos' => '?',
            'App\\Controller\\RoutesController::deleteAsConsultasProcedimientos' => '?',
            'App\\Controller\\RoutesController::edit' => '?',
            'App\\Controller\\RoutesController::fetchData' => '?',
            'App\\Controller\\RoutesController::typesValidation' => '?',
            'App\\Controller\\RoutesController::updateAsConsultasProcedimientos' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ExampleController:causaExterna' => '?',
            'App\\Controller\\ExampleController:cupsData' => '?',
            'App\\Controller\\ExampleController:diagnosticoSuggestions' => '?',
            'App\\Controller\\ExampleController:exportData' => '?',
            'App\\Controller\\ExampleController:finalidadData' => '?',
            'App\\Controller\\ExampleController:index' => '?',
            'App\\Controller\\RoutesController:createAsConsultasProcedimientos' => '?',
            'App\\Controller\\RoutesController:deleteAsConsultasProcedimientos' => '?',
            'App\\Controller\\RoutesController:edit' => '?',
            'App\\Controller\\RoutesController:fetchData' => '?',
            'App\\Controller\\RoutesController:typesValidation' => '?',
            'App\\Controller\\RoutesController:updateAsConsultasProcedimientos' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
