<?php

namespace ContainerIJdfZVd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZIDK9ptService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zIDK9pt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zIDK9pt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'finalidadRepository' => ['privates', 'App\\Repository\\RipsTablaReferenciaFinalidadConsultaV2Repository', 'getRipsTablaReferenciaFinalidadConsultaV2RepositoryService', true],
        ], [
            'finalidadRepository' => 'App\\Repository\\RipsTablaReferenciaFinalidadConsultaV2Repository',
        ]);
    }
}
