<?php

namespace ContainerCN2TDkx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2XT1KAKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2XT1KAK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2XT1KAK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'asCie10Repository' => ['privates', 'App\\Repository\\AsCie10Repository', 'getAsCie10RepositoryService', true],
            'asConsultasRepository' => ['privates', 'App\\Repository\\AsConsultasProcedimientosRepository', 'getAsConsultasProcedimientosRepositoryService', true],
            'asCupsRepository' => ['privates', 'App\\Repository\\AsCupsRepository', 'getAsCupsRepositoryService', true],
            'causaExternaRepository' => ['privates', 'App\\Repository\\RipsTablaReferenciaCausaExternaV2Repository', 'getRipsTablaReferenciaCausaExternaV2RepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'finalidadRepository' => ['privates', 'App\\Repository\\RipsTablaReferenciaFinalidadConsultaV2Repository', 'getRipsTablaReferenciaFinalidadConsultaV2RepositoryService', true],
            'servicioRepository' => ['privates', 'App\\Repository\\RipsTablaReferenciaServicioRepository', 'getRipsTablaReferenciaServicioRepositoryService', true],
            'validationService' => ['privates', 'App\\Service\\ValidationServices', 'getValidationServicesService', true],
        ], [
            'asCie10Repository' => 'App\\Repository\\AsCie10Repository',
            'asConsultasRepository' => 'App\\Repository\\AsConsultasProcedimientosRepository',
            'asCupsRepository' => 'App\\Repository\\AsCupsRepository',
            'causaExternaRepository' => 'App\\Repository\\RipsTablaReferenciaCausaExternaV2Repository',
            'entityManager' => '?',
            'finalidadRepository' => 'App\\Repository\\RipsTablaReferenciaFinalidadConsultaV2Repository',
            'servicioRepository' => 'App\\Repository\\RipsTablaReferenciaServicioRepository',
            'validationService' => 'App\\Service\\ValidationServices',
        ]);
    }
}
