<?php

namespace ContainerCN2TDkx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AMtaBc3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AMtaBc3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AMtaBc3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'consultas' => ['privates', 'App\\Repository\\AsConsultasProcedimientosRepository', 'getAsConsultasProcedimientosRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'consultas' => 'App\\Repository\\AsConsultasProcedimientosRepository',
            'em' => '?',
        ]);
    }
}
