<?php

namespace ContainerCN2TDkx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_B1F7hHLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.B1F7hHL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.B1F7hHL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'causaRepository' => ['privates', 'App\\Repository\\RipsTablaReferenciaCausaExternaV2Repository', 'getRipsTablaReferenciaCausaExternaV2RepositoryService', true],
        ], [
            'causaRepository' => 'App\\Repository\\RipsTablaReferenciaCausaExternaV2Repository',
        ]);
    }
}
