<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBxwxNLi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBxwxNLi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBxwxNLi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBxwxNLi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBxwxNLi\App_KernelDevDebugContainer([
    'container.build_hash' => 'BxwxNLi',
    'container.build_id' => '4e39361b',
    'container.build_time' => 1737967526,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBxwxNLi');
