<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCN2TDkx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCN2TDkx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCN2TDkx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCN2TDkx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCN2TDkx\App_KernelDevDebugContainer([
    'container.build_hash' => 'CN2TDkx',
    'container.build_id' => '3fd8af68',
    'container.build_time' => 1738274983,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCN2TDkx');
