<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'index' => [[], ['_controller' => 'App\\Controller\\ListCupsRipsController::index'], [], [['text', '/']], [], [], []],
    'get_list_diagnostic' => [[], ['_controller' => 'App\\Controller\\ListCupsRipsController::diagnosticoSuggestions'], [], [['text', '/list-diagnostic']], [], [], []],
    'get_list_external_cause' => [[], ['_controller' => 'App\\Controller\\ListCupsRipsController::causaExterna'], [], [['text', '/list-external-cause']], [], [], []],
    'get_list_finality' => [[], ['_controller' => 'App\\Controller\\ListCupsRipsController::finalidadData'], [], [['text', '/list-finality']], [], [], []],
    'get_list_as_cups' => [[], ['_controller' => 'App\\Controller\\ListCupsRipsController::cupsData'], [], [['text', '/list-cups']], [], [], []],
    'export_data' => [[], ['_controller' => 'App\\Controller\\ListCupsRipsController::exportData'], [], [['text', '/export']], [], [], []],
    'get_as_consults' => [[], ['_controller' => 'App\\Controller\\RoutesController::fetchData'], [], [['text', '/get-consults']], [], [], []],
    'get_as_consult_by_id' => [['id'], ['_controller' => 'App\\Controller\\RoutesController::edit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/get-consult']], [], [], []],
    'create_as_consult' => [[], ['_controller' => 'App\\Controller\\RoutesController::createAsConsultasProcedimientos'], [], [['text', '/create-consult']], [], [], []],
    'update_as_consult' => [['id'], ['_controller' => 'App\\Controller\\RoutesController::updateAsConsultasProcedimientos'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/update-consult']], [], [], []],
    'delete_as_consult' => [['id'], ['_controller' => 'App\\Controller\\RoutesController::deleteAsConsultasProcedimientos'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/delete-consult']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
];
