<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AsConsultasProcedimientos extends \App\Entity\AsConsultasProcedimientos implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'causa_externa' => [parent::class, 'causa_externa', null],
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null],
        "\0".parent::class."\0".'created_by' => [parent::class, 'created_by', null],
        "\0".parent::class."\0".'cups' => [parent::class, 'cups', null],
        "\0".parent::class."\0".'diagnostico_defaults' => [parent::class, 'diagnostico_defaults', null],
        "\0".parent::class."\0".'finalidad' => [parent::class, 'finalidad', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'informe_oportunidad' => [parent::class, 'informe_oportunidad', null],
        "\0".parent::class."\0".'servicio_rips_code' => [parent::class, 'servicio_rips_code', null],
        "\0".parent::class."\0".'tipo_cita' => [parent::class, 'tipo_cita', null],
        "\0".parent::class."\0".'tipo_diagnostico' => [parent::class, 'tipo_diagnostico', null],
        "\0".parent::class."\0".'tipo_servicio' => [parent::class, 'tipo_servicio', null],
        'causa_externa' => [parent::class, 'causa_externa', null],
        'created_at' => [parent::class, 'created_at', null],
        'created_by' => [parent::class, 'created_by', null],
        'cups' => [parent::class, 'cups', null],
        'diagnostico_defaults' => [parent::class, 'diagnostico_defaults', null],
        'finalidad' => [parent::class, 'finalidad', null],
        'id' => [parent::class, 'id', null],
        'informe_oportunidad' => [parent::class, 'informe_oportunidad', null],
        'servicio_rips_code' => [parent::class, 'servicio_rips_code', null],
        'tipo_cita' => [parent::class, 'tipo_cita', null],
        'tipo_diagnostico' => [parent::class, 'tipo_diagnostico', null],
        'tipo_servicio' => [parent::class, 'tipo_servicio', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
