<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AsCups extends \App\Entity\AsCups implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'capitulo' => [parent::class, 'capitulo', null],
        "\0".parent::class."\0".'codigo_cups' => [parent::class, 'codigo_cups', null],
        "\0".parent::class."\0".'consultasProcedimientos' => [parent::class, 'consultasProcedimientos', null],
        "\0".parent::class."\0".'descripcion_cups' => [parent::class, 'descripcion_cups', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'seccion' => [parent::class, 'seccion', null],
        'capitulo' => [parent::class, 'capitulo', null],
        'codigo_cups' => [parent::class, 'codigo_cups', null],
        'consultasProcedimientos' => [parent::class, 'consultasProcedimientos', null],
        'descripcion_cups' => [parent::class, 'descripcion_cups', null],
        'id' => [parent::class, 'id', null],
        'seccion' => [parent::class, 'seccion', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
